CREATE DATABASE DA_WIN_NANGCAO
GO
use DA_WIN_NANGCAO
GO
CREATE TABLE CHUCVU
(
	MACHUCVU  NVARCHAR(10) NOT NULL,
	TENCHUCVU NVARCHAR(50),
	
	PRIMARY KEY (MACHUCVU),
);

CREATE TABLE PHONGBAN
(
	MAPHONGBAN  NVARCHAR(10) NOT NULL,
	TENPHONGBAN NVARCHAR(50),
	PRIMARY KEY (MAPHONGBAN),
);

CREATE TABLE CHUYENMON
(
	MACHUYENMON  NVARCHAR(10) NOT NULL,
	TENCHUYENMON NVARCHAR(50),
	PRIMARY KEY (MACHUYENMON),
);
CREATE TABLE CHITIETCHUYENMON
(
	MACHUYENMON  NVARCHAR(10) NOT NULL,
	MANV  NVARCHAR(10) NOT NULL,
	PRIMARY KEY (MACHUYENMON,MANV)
);

CREATE TABLE TRINHDOHOCVAN
(
	MATRINHDOHOCVAN  NVARCHAR(10) NOT NULL,
	TENTRINHDOHOCVAN NVARCHAR(50),
	PRIMARY KEY (MATRINHDOHOCVAN),
);

CREATE TABLE TRINHDOTINHOC
(
	MATRINHDOTINHOC  NVARCHAR(10) NOT NULL,
	TENTRINHDOTINHOC NVARCHAR(50),
	PRIMARY KEY (MATRINHDOTINHOC),
);

CREATE TABLE NGOAINGU
(
	MANGOAINGU  NVARCHAR(10) NOT NULL,
	TENNGOAINGU  NVARCHAR(50) ,
	PRIMARY KEY (MANGOAINGU)
);

CREATE TABLE CHITIETNGOAINGU
(
	MACHITIETNGOAINGU NVARCHAR(10) NOT NULL,
	MANGOAINGU  NVARCHAR(10) NOT NULL,
	TRINHDO NVARCHAR(50)
	PRIMARY KEY (MACHITIETNGOAINGU)
);

CREATE TABLE DANTOC
(
	MADANTOC NVARCHAR(10) NOT NULL,
	TENDANTOC NVARCHAR(50),
	PRIMARY KEY (MADANTOC),
);

CREATE TABLE TONGIAO
(
	MATONGIAO  NVARCHAR(10) NOT NULL,
	TENTONGIAO NVARCHAR(50),
	PRIMARY KEY (MATONGIAO),
	
);

CREATE TABLE QUOCTICH
(
	MAQUOCTICH  NVARCHAR(10) NOT NULL,
	TENQUOCTICH NVARCHAR(50),
	PRIMARY KEY (MAQUOCTICH),
);


CREATE TABLE NHANVIEN
(
	MANV  NVARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50),
	MAPHONGBAN  NVARCHAR(10) NOT NULL,
	MACHUCVU  NVARCHAR(10) NOT NULL,
	MATRINHDOHOCVAN  NVARCHAR(10) NOT NULL,
	MATRINHDOTINHOC NVARCHAR(10) NOT NULL,
	MACHITIETNGOAINGU NVARCHAR(10) NOT NULL,
	MADANTOC NVARCHAR(10) NOT NULL,
	MATONGIAO  NVARCHAR(10) NOT NULL,
	MAQUOCTICH  NVARCHAR(10) NOT NULL,
	NGAYVAOLAM DATE,
	GIOITINH NVARCHAR(10),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	QUEQUAN NVARCHAR(50),
	CMND INT,
	EMAIL NVARCHAR(50),
	SDT INT,
	TINHTRANG NVARCHAR(50),
	PRIMARY KEY (MANV)
);
CREATE TABLE QUYEN
(
	MAQUYEN  NVARCHAR(10) NOT NULL,
	TENQUYEN NVARCHAR(50),
	PRIMARY KEY (MAQUYEN),
	
);
CREATE TABLE TAIKHOAN
(
	MANV  NVARCHAR(10) NOT NULL,
	MATKHAU NVARCHAR(10),
	MAQUYEN NVARCHAR(10) NOT NULL,
	PRIMARY KEY (MANV)
);

CREATE TABLE HOPDONGLAODONG
(
	MAHOPDONG  NVARCHAR(10) NOT NULL,
	TENHOPDONG NVARCHAR(50),
	PRIMARY KEY (MAHOPDONG),
);

CREATE TABLE CHITIETHOPDONG
(
	MACTHD NVARCHAR(10) NOT NULL,
	MAHOPDONG  NVARCHAR(10) NOT NULL,
	MANV NVARCHAR(10)NOT NULL,
	KYLANTHU INT,
	NGAYKY DATE,
	NGAYBD DATE,
	NGAYKT DATE,
	LUONGTHOATHUAN MONEY,
	PRIMARY KEY (MACTHD)
);

ALTER TABLE CHITIETHOPDONG

ADD CONSTRAINT MACDINH_TTTL DEFAULT (0) FOR LUONGTHOATHUAN

CREATE TABLE LOAIKHENTHUONG
(
	MALOAIKHENTHUONG  NVARCHAR(10) NOT NULL,
	LOAITENKHENTHUONG NVARCHAR (50),
	TIENTHUONG MONEY,
	PRIMARY KEY (MALOAIKHENTHUONG),
);

ALTER TABLE LOAIKHENTHUONG
ADD CONSTRAINT MACDINH_TTTTL DEFAULT (0) FOR TIENTHUONG

CREATE TABLE CHITIETKHENTHUONG
(
	MACTKHENTHUONG  NVARCHAR(10) NOT NULL,
	MALOAIKHENTHUONG  NVARCHAR(10) NOT NULL,
	MANV NVARCHAR(10)NOT NULL,
	NGAYKHENTHUONG DATE,
	PRIMARY KEY (MACTKHENTHUONG)
);




CREATE TABLE DAOTAO
(
	MAKHOADAOTAO  NVARCHAR(10) NOT NULL,
	TENKHOADAOTAO NVARCHAR(50) ,
	LANDAOTAO INT,
	PRIMARY KEY (MAKHOADAOTAO)
);

CREATE TABLE CHUONGTRINHDAOTAO
(
	MACTKHOADAOTAO  NVARCHAR(10) NOT NULL,
	MAKHOADAOTAO  NVARCHAR(10) NOT NULL,
	MANV NVARCHAR(10)NOT NULL,
	NGAYBD DATE,
	NGAYKT DATE,
	PRIMARY KEY (MACTKHOADAOTAO)
);

CREATE TABLE BAOHIEM
(
	MABAOHIEM  NVARCHAR(10) NOT NULL,
	MANV NVARCHAR(10)NOT NULL,
	LOAIBAOHIEM NVARCHAR(50) ,
	NOICAP NVARCHAR(50) ,
	NOIKHAM NVARCHAR(50) ,
	NGAYDK DATE,
	NGAYHH DATE,
	PRIMARY KEY (MABAOHIEM)
);

CREATE TABLE LOAICONG
(
	MALOAI NVARCHAR(10) NOT NULL,
	TENLOAI NVARCHAR(50) ,
	HESO FLOAT,
	PRIMARY KEY (MALOAI)
);

CREATE TABLE BANGCHAMCONG
(
	MABANGCHAMCONG NVARCHAR(10) NOT NULL,
	MANV NVARCHAR(10),
	MALOAI NVARCHAR(10) ,
	NGAYLAM DATE,
	GIOVAO TIME,
	GIORA TIME,
	PRIMARY KEY (MABANGCHAMCONG)
);

--CREATE TABLE PHUCAP
--(
----	MAPHUCAP NVARCHAR(10) NOT NULL,
--	TENPHUCAP NVARCHAR(50) ,
--	TIENPHUCAP INT,
--	PRIMARY KEY (MAPHUCAP)
--);

CREATE TABLE DANHMUCTANGCA
(
	MALOAICA NVARCHAR(10) NOT NULL,
	TENLOAICA NVARCHAR(50) ,
	HESO INT,
	SOGIOTANGCA FLOAT, ---CHI HIEN LEN CHO THAY
	PRIMARY KEY (MALOAICA)
);

CREATE TABLE BANGTANGCA
(
	MANV NVARCHAR(10) ,
	NGAYTANGCA DATE,
	MALOAICA NVARCHAR(10) ,
	PRIMARY KEY (MANV,NGAYTANGCA)
);

CREATE TABLE BANGTANGLUONG
(
	MABANGTANGLUONG NVARCHAR(10) NOT NULL,
	MANV NVARCHAR(10)NOT NULL,
	NGAYBD DATE,
	MUCTANG FLOAT,
	TONGTIENTANG MONEY,
	TANGLANTHU INT,
	PRIMARY KEY (MABANGTANGLUONG)
);

ALTER TABLE BANGTANGLUONG
ADD CONSTRAINT MACDINH_TTL DEFAULT (0) FOR TONGTIENTANG


CREATE TABLE TONGLUONG
(
	MANV NVARCHAR(10)NOT NULL,
	LUONGTHANG NVARCHAR(10),
	TONGTIENLUONG MONEY,
	PRIMARY KEY (MANV,LUONGTHANG)
);

ALTER TABLE TONGLUONG
ADD CONSTRAINT MACDINH_TL DEFAULT (0) FOR TONGTIENLUONG

CREATE TABLE DS_KYLUAT
(
	MAKYLUAT NVARCHAR(10)NOT NULL,
	TENKYLUAT NVARCHAR(50),
	TIENKYLUAT MONEY,
	PRIMARY KEY (MAKYLUAT)
);

CREATE TABLE QUANLYKYLUAT
(
	MAQUANLYKYLUAT NVARCHAR(10)NOT NULL,
	MANV NVARCHAR(10),
	MAKYLUAT NVARCHAR(10)NOT NULL,
	NGAYKYLUAT DATE,
	COQUANKYLUAT NVARCHAR(50),
	PRIMARY KEY (MAQUANLYKYLUAT)
);


CREATE TABLE QUANLYNGHIVIEC
(
	MAQUANLYNGHIVIEC NVARCHAR(10)NOT NULL,
	MANV NVARCHAR(10),
	SOQUYETDINH INT,
	NGAYQUYETDINH DATE,
	NGUOIKY NVARCHAR(50),
	NGAYNGHIVIEC DATE,
	LYDO NVARCHAR(50),
	PRIMARY KEY (MAQUANLYNGHIVIEC,MANV)
);

CREATE TABLE QUANLYTHAISAN
(
	MAQUANLYTHAISAN NVARCHAR(10)NOT NULL,
	MANV NVARCHAR(10),
	SOQUYETDINH INT,
	SINHCONTHU INT,
	NGAYQUYETDINH DATE,
	COQUANQUYETDINH NVARCHAR(50),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	PRIMARY KEY (MAQUANLYTHAISAN)
);


CREATE TABLE HOSOTUYENDUNG
(
	MAUNGVIEN NVARCHAR(10)NOT NULL,
	MADANTOC NVARCHAR(10) NOT NULL,
	MATONGIAO  NVARCHAR(10) NOT NULL,
	MAQUOCTICH  NVARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(10),
	NGAYSINH DATE,
	NOISINH NVARCHAR(50),
	CMND INT,
	NGAYCAP DATE,
	NOICAP NVARCHAR(50),
	QUEQUAN NVARCHAR(50),
	DIACHITHUONGTRU NVARCHAR(50),
	NOIOHIENTAI NVARCHAR(50),
	DIENTHOAI INT,
	EMAIL NVARCHAR(50),
	TINHTRANGHONNHAN NVARCHAR(10),
	DIENUUTIEN NVARCHAR(50),
	TINHTRANGSUCKHOE NVARCHAR(50),
	NGAYTUYENDUNG DATE,
	HINHTHUCTUYENDUNG NVARCHAR(50),
	VITRITUYENDUNG NVARCHAR(50),
	MACHITIETNGOAINGU NVARCHAR(10),
	MATRINHDOHOCVAN  NVARCHAR(10),
	MATRINHDOTINHOC  NVARCHAR(10),
	PRIMARY KEY (MAUNGVIEN)
	
);

CREATE TABLE KQ_TUYENDUNG
(
	MAKQ NVARCHAR(10)NOT NULL,
	MAUNGVIEN NVARCHAR(10)NOT NULL,
	KETQUA NVARCHAR(50),
	PRIMARY KEY (MAKQ,MAUNGVIEN)
);

CREATE TABLE HINHANH
(
	MAHINHANH NVARCHAR(10)NOT NULL,
	TENHINHANH NVARCHAR(10),
	URL TEXT NOT NULL,
	MANV NVARCHAR(10),
	MAUNGVIEN NVARCHAR(10),
	PRIMARY KEY (MAHINHANH)

);


ALTER TABLE CHITIETCHUYENMON
ADD FOREIGN KEY(MACHUYENMON)REFERENCES CHUYENMON(MACHUYENMON),
	FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV)

ALTER TABLE CHITIETNGOAINGU
ADD FOREIGN KEY(MANGOAINGU)REFERENCES NGOAINGU(MANGOAINGU)

ALTER TABLE NHANVIEN
ADD FOREIGN KEY(MAPHONGBAN)REFERENCES PHONGBAN(MAPHONGBAN),
	FOREIGN KEY(MACHUCVU)REFERENCES CHUCVU(MACHUCVU),
	FOREIGN KEY(MATRINHDOTINHOC)REFERENCES TRINHDOTINHOC(MATRINHDOTINHOC),
	FOREIGN KEY(MACHITIETNGOAINGU)REFERENCES CHITIETNGOAINGU(MACHITIETNGOAINGU),
	FOREIGN KEY(MATRINHDOHOCVAN)REFERENCES TRINHDOHOCVAN(MATRINHDOHOCVAN),
	FOREIGN KEY(MADANTOC)REFERENCES DANTOC(MADANTOC),
	FOREIGN KEY(MATONGIAO)REFERENCES TONGIAO(MATONGIAO),
	FOREIGN KEY(MAQUOCTICH)REFERENCES QUOCTICH(MAQUOCTICH)

ALTER TABLE TAIKHOAN
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MAQUYEN)REFERENCES QUYEN(MAQUYEN)

ALTER TABLE CHITIETHOPDONG
ADD FOREIGN KEY(MAHOPDONG)REFERENCES HOPDONGLAODONG(MAHOPDONG),
	FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV)

ALTER TABLE CHITIETKHENTHUONG
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MALOAIKHENTHUONG)REFERENCES LOAIKHENTHUONG(MALOAIKHENTHUONG)
	

ALTER TABLE CHUONGTRINHDAOTAO
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MAKHOADAOTAO)REFERENCES DAOTAO(MAKHOADAOTAO)

ALTER TABLE BAOHIEM
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV)

ALTER TABLE BANGCHAMCONG
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MALOAI)REFERENCES LOAICONG(MALOAI)

ALTER TABLE BANGTANGCA
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MALOAICA)REFERENCES DANHMUCTANGCA(MALOAICA)

ALTER TABLE BANGTANGLUONG
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV)

ALTER TABLE TONGLUONG
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV)

ALTER TABLE QUANLYKYLUAT
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MAKYLUAT)REFERENCES DS_KYLUAT(MAKYLUAT)

ALTER TABLE QUANLYNGHIVIEC
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV)

ALTER TABLE QUANLYTHAISAN
ADD FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV)

ALTER TABLE HOSOTUYENDUNG
ADD FOREIGN KEY(MACHITIETNGOAINGU)REFERENCES CHITIETNGOAINGU(MACHITIETNGOAINGU),
	FOREIGN KEY(MATRINHDOHOCVAN)REFERENCES TRINHDOHOCVAN(MATRINHDOHOCVAN),
	FOREIGN KEY(MATRINHDOTINHOC)REFERENCES TRINHDOTINHOC(MATRINHDOTINHOC),
	FOREIGN KEY(MADANTOC)REFERENCES DANTOC(MADANTOC),
	FOREIGN KEY(MATONGIAO)REFERENCES TONGIAO(MATONGIAO),
	FOREIGN KEY(MAQUOCTICH)REFERENCES QUOCTICH(MAQUOCTICH)

ALTER TABLE KQ_TUYENDUNG
ADD FOREIGN KEY(MAUNGVIEN)REFERENCES HOSOTUYENDUNG(MAUNGVIEN)

ALTER TABLE HINHANH
ADD FOREIGN KEY(MAUNGVIEN)REFERENCES HOSOTUYENDUNG(MAUNGVIEN),
	FOREIGN KEY(MANV)REFERENCES NHANVIEN(MANV)

------------------------------------------------------------------------------------
-----------------------------------TRIGGER------------------------------------------

/*
CREATE TRIGGER TONG_TIENLUON_TANG
ON BANGTANGLUONG
FOR  INSERT, UPDATE
AS
BEGIN
	UPDATE BANGTANGLUONG
	SET TONGTIENTANG =(SELECT LUONGTHOATHUAN FROM CHITIETHOPDONG,inserted WHERE MANV=CHITIETHOPDONG.MANV AND inserted.MANV=MANV ) *MUCTANG +(SELECT LUONGTHOATHUAN FROM CHITIETHOPDONG,inserted WHERE CHITIETHOPDONG.MANV=MANV AND inserted.MANV=MANV)
	WHERE MANV =(SELECT MANV FROM inserted)
END
*/
