<?xml version="1.0" encoding="utf-8"?><Database Name="DA_WIN_NANGCAO" Class="LinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.BANGCHAMCONG" Member="BANGCHAMCONGs">
    <Type Name="BANGCHAMCONG">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAM" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GIOVAO" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="GIORA" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="NHANVIEN_BANGCHAMCONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BANGTANGCA" Member="BANGTANGCAs">
    <Type Name="BANGTANGCA">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYTANGCA" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAICA" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="DANHMUCTANGCA_BANGTANGCA" Member="DANHMUCTANGCA" ThisKey="MALOAICA" OtherKey="MALOAICA" Type="DANHMUCTANGCA" IsForeignKey="true" />
      <Association Name="NHANVIEN_BANGTANGCA" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BANGTANGLUONG" Member="BANGTANGLUONGs">
    <Type Name="BANGTANGLUONG">
      <Column Name="MABANGTANGLUONG" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYBD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MUCTANG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TONGTIENTANG" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TANGLANTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_BANGTANGLUONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BAOHIEM" Member="BAOHIEMs">
    <Type Name="BAOHIEM">
      <Column Name="MABAOHIEM" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LOAIBAOHIEM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOICAP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOIKHAM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYDK" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYHH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NHANVIEN_BAOHIEM" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETCHUYENMON" Member="CHITIETCHUYENMONs">
    <Type Name="CHITIETCHUYENMON">
      <Column Name="MACHUYENMON" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAUNGVIEN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CHUYENMON_CHITIETCHUYENMON" Member="CHUYENMON" ThisKey="MACHUYENMON" OtherKey="MACHUYENMON" Type="CHUYENMON" IsForeignKey="true" />
      <Association Name="HOSOTUYENDUNG_CHITIETCHUYENMON" Member="HOSOTUYENDUNG" ThisKey="MAUNGVIEN" OtherKey="MAUNGVIEN" Type="HOSOTUYENDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOPDONG" Member="CHITIETHOPDONGs">
    <Type Name="CHITIETHOPDONG">
      <Column Name="MACTHD" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHOPDONG" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="KYLANTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYKY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYBD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LUONGTHOATHUAN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HOPDONGLAODONG_CHITIETHOPDONG" Member="HOPDONGLAODONG" ThisKey="MAHOPDONG" OtherKey="MAHOPDONG" Type="HOPDONGLAODONG" IsForeignKey="true" />
      <Association Name="NHANVIEN_CHITIETHOPDONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETKHENTHUONG" Member="CHITIETKHENTHUONGs">
    <Type Name="CHITIETKHENTHUONG">
      <Column Name="MACTKHENTHUONG" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIKHENTHUONG" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYKHENTHUONG" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="LOAIKHENTHUONG_CHITIETKHENTHUONG" Member="LOAIKHENTHUONG" ThisKey="MALOAIKHENTHUONG" OtherKey="MALOAIKHENTHUONG" Type="LOAIKHENTHUONG" IsForeignKey="true" />
      <Association Name="NHANVIEN_CHITIETKHENTHUONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETNGOAINGU" Member="CHITIETNGOAINGUs">
    <Type Name="CHITIETNGOAINGU">
      <Column Name="MANGOAINGU" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAUNGVIEN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="HOSOTUYENDUNG_CHITIETNGOAINGU" Member="HOSOTUYENDUNG" ThisKey="MAUNGVIEN" OtherKey="MAUNGVIEN" Type="HOSOTUYENDUNG" IsForeignKey="true" />
      <Association Name="NGOAINGU_CHITIETNGOAINGU" Member="NGOAINGU" ThisKey="MANGOAINGU" OtherKey="MANGOAINGU" Type="NGOAINGU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUCVU" Member="CHUCVUs">
    <Type Name="CHUCVU">
      <Column Name="MACHUCVU" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCHUCVU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CHUCVU_NHANVIEN" Member="NHANVIENs" ThisKey="MACHUCVU" OtherKey="MACHUCVU" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.CHUONGTRINHDAOTAO" Member="CHUONGTRINHDAOTAOs">
    <Type Name="CHUONGTRINHDAOTAO">
      <Column Name="MACTKHOADAOTAO" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKHOADAOTAO" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYBD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DAOTAO_CHUONGTRINHDAOTAO" Member="DAOTAO" ThisKey="MAKHOADAOTAO" OtherKey="MAKHOADAOTAO" Type="DAOTAO" IsForeignKey="true" />
      <Association Name="NHANVIEN_CHUONGTRINHDAOTAO" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUYENMON" Member="CHUYENMONs">
    <Type Name="CHUYENMON">
      <Column Name="MACHUYENMON" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCHUYENMON" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CHUYENMON_CHITIETCHUYENMON" Member="CHITIETCHUYENMONs" ThisKey="MACHUYENMON" OtherKey="MACHUYENMON" Type="CHITIETCHUYENMON" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUCTANGCA" Member="DANHMUCTANGCAs">
    <Type Name="DANHMUCTANGCA">
      <Column Name="MALOAICA" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAICA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HESO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOGIOTANGCA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DANHMUCTANGCA_BANGTANGCA" Member="BANGTANGCAs" ThisKey="MALOAICA" OtherKey="MALOAICA" Type="BANGTANGCA" />
    </Type>
  </Table>
  <Table Name="dbo.DANTOC" Member="DANTOCs">
    <Type Name="DANTOC">
      <Column Name="MADANTOC" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDANTOC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DANTOC_HOSOTUYENDUNG" Member="HOSOTUYENDUNGs" ThisKey="MADANTOC" OtherKey="MADANTOC" Type="HOSOTUYENDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.DAOTAO" Member="DAOTAOs">
    <Type Name="DAOTAO">
      <Column Name="MAKHOADAOTAO" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKHOADAOTAO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DAOTAO_CHUONGTRINHDAOTAO" Member="CHUONGTRINHDAOTAOs" ThisKey="MAKHOADAOTAO" OtherKey="MAKHOADAOTAO" Type="CHUONGTRINHDAOTAO" />
    </Type>
  </Table>
  <Table Name="dbo.DS_KYLUAT" Member="DS_KYLUATs">
    <Type Name="DS_KYLUAT">
      <Column Name="MAKYLUAT" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKYLUAT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HINHTHUC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TIENKYLUAT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DS_KYLUAT_QUANLYKYLUAT" Member="QUANLYKYLUATs" ThisKey="MAKYLUAT" OtherKey="MAKYLUAT" Type="QUANLYKYLUAT" />
    </Type>
  </Table>
  <Table Name="dbo.HINHANH" Member="HINHANHs">
    <Type Name="HINHANH">
      <Column Name="MAHINHANH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENHINHANH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MAUNGVIEN" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="HOSOTUYENDUNG_HINHANH" Member="HOSOTUYENDUNG" ThisKey="MAUNGVIEN" OtherKey="MAUNGVIEN" Type="HOSOTUYENDUNG" IsForeignKey="true" />
      <Association Name="NHANVIEN_HINHANH" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOPDONGLAODONG" Member="HOPDONGLAODONGs">
    <Type Name="HOPDONGLAODONG">
      <Column Name="MAHOPDONG" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENHOPDONG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HOPDONGLAODONG_CHITIETHOPDONG" Member="CHITIETHOPDONGs" ThisKey="MAHOPDONG" OtherKey="MAHOPDONG" Type="CHITIETHOPDONG" />
    </Type>
  </Table>
  <Table Name="dbo.HOSOTUYENDUNG" Member="HOSOTUYENDUNGs">
    <Type Name="HOSOTUYENDUNG">
      <Column Name="MAUNGVIEN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MADANTOC" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MATONGIAO" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAQUOCTICH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NOISINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYCAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NOICAP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QUEQUAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHITHUONGTRU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOIOHIENTAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TINHTRANGHONNHAN" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DIENUUTIEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TINHTRANGSUCKHOE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYTUYENDUNG" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HINHTHUCTUYENDUNG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VITRITUYENDUNG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MATRINHDOHOCVAN" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MATRINHDOTINHOC" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="HOSOTUYENDUNG_CHITIETCHUYENMON" Member="CHITIETCHUYENMONs" ThisKey="MAUNGVIEN" OtherKey="MAUNGVIEN" Type="CHITIETCHUYENMON" />
      <Association Name="HOSOTUYENDUNG_CHITIETNGOAINGU" Member="CHITIETNGOAINGUs" ThisKey="MAUNGVIEN" OtherKey="MAUNGVIEN" Type="CHITIETNGOAINGU" />
      <Association Name="HOSOTUYENDUNG_HINHANH" Member="HINHANHs" ThisKey="MAUNGVIEN" OtherKey="MAUNGVIEN" Type="HINHANH" />
      <Association Name="HOSOTUYENDUNG_KQ_TUYENDUNG" Member="KQ_TUYENDUNGs" ThisKey="MAUNGVIEN" OtherKey="MAUNGVIEN" Type="KQ_TUYENDUNG" />
      <Association Name="HOSOTUYENDUNG_NHANVIEN" Member="NHANVIENs" ThisKey="MAUNGVIEN" OtherKey="MAHOSO" Type="NHANVIEN" />
      <Association Name="DANTOC_HOSOTUYENDUNG" Member="DANTOC" ThisKey="MADANTOC" OtherKey="MADANTOC" Type="DANTOC" IsForeignKey="true" />
      <Association Name="QUOCTICH_HOSOTUYENDUNG" Member="QUOCTICH" ThisKey="MAQUOCTICH" OtherKey="MAQUOCTICH" Type="QUOCTICH" IsForeignKey="true" />
      <Association Name="TONGIAO_HOSOTUYENDUNG" Member="TONGIAO" ThisKey="MATONGIAO" OtherKey="MATONGIAO" Type="TONGIAO" IsForeignKey="true" />
      <Association Name="TRINHDOHOCVAN_HOSOTUYENDUNG" Member="TRINHDOHOCVAN" ThisKey="MATRINHDOHOCVAN" OtherKey="MATRINHDOHOCVAN" Type="TRINHDOHOCVAN" IsForeignKey="true" />
      <Association Name="TRINHDOTINHOC_HOSOTUYENDUNG" Member="TRINHDOTINHOC" ThisKey="MATRINHDOTINHOC" OtherKey="MATRINHDOTINHOC" Type="TRINHDOTINHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KQ_TUYENDUNG" Member="KQ_TUYENDUNGs">
    <Type Name="KQ_TUYENDUNG">
      <Column Name="MAKQ" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAUNGVIEN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KETQUA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HOSOTUYENDUNG_KQ_TUYENDUNG" Member="HOSOTUYENDUNG" ThisKey="MAUNGVIEN" OtherKey="MAUNGVIEN" Type="HOSOTUYENDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIKHENTHUONG" Member="LOAIKHENTHUONGs">
    <Type Name="LOAIKHENTHUONG">
      <Column Name="MALOAIKHENTHUONG" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LOAITENKHENTHUONG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TIENTHUONG" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="LOAIKHENTHUONG_CHITIETKHENTHUONG" Member="CHITIETKHENTHUONGs" ThisKey="MALOAIKHENTHUONG" OtherKey="MALOAIKHENTHUONG" Type="CHITIETKHENTHUONG" />
    </Type>
  </Table>
  <Table Name="dbo.MANHINH" Member="MANHINHs">
    <Type Name="MANHINH">
      <Column Name="MAMANHINH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENMANHINH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MANHINH_PHANQUYEN" Member="PHANQUYENs" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.NGOAINGU" Member="NGOAINGUs">
    <Type Name="NGOAINGU">
      <Column Name="MANGOAINGU" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNGOAINGU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NGOAINGU_CHITIETNGOAINGU" Member="CHITIETNGOAINGUs" ThisKey="MANGOAINGU" OtherKey="MANGOAINGU" Type="CHITIETNGOAINGU" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNGNHOMNGUOIDUNG" Member="NGUOIDUNGNHOMNGUOIDUNGs">
    <Type Name="NGUOIDUNGNHOMNGUOIDUNG">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOM" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NHOMNGUOIDUNG_NGUOIDUNGNHOMNGUOIDUNG" Member="NHOMNGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="NHOMNGUOIDUNG" IsForeignKey="true" />
      <Association Name="TAIKHOAN_NGUOIDUNGNHOMNGUOIDUNG" Member="TAIKHOAN" ThisKey="MANV" OtherKey="MANV" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAPHONGBAN" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MACHUCVU" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYVAOLAM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAHOSO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="NHANVIEN_BANGCHAMCONG" Member="BANGCHAMCONGs" ThisKey="MANV" OtherKey="MANV" Type="BANGCHAMCONG" />
      <Association Name="NHANVIEN_BANGTANGCA" Member="BANGTANGCAs" ThisKey="MANV" OtherKey="MANV" Type="BANGTANGCA" />
      <Association Name="NHANVIEN_BANGTANGLUONG" Member="BANGTANGLUONGs" ThisKey="MANV" OtherKey="MANV" Type="BANGTANGLUONG" />
      <Association Name="NHANVIEN_BAOHIEM" Member="BAOHIEMs" ThisKey="MANV" OtherKey="MANV" Type="BAOHIEM" />
      <Association Name="NHANVIEN_CHITIETHOPDONG" Member="CHITIETHOPDONGs" ThisKey="MANV" OtherKey="MANV" Type="CHITIETHOPDONG" />
      <Association Name="NHANVIEN_CHITIETKHENTHUONG" Member="CHITIETKHENTHUONGs" ThisKey="MANV" OtherKey="MANV" Type="CHITIETKHENTHUONG" />
      <Association Name="NHANVIEN_CHUONGTRINHDAOTAO" Member="CHUONGTRINHDAOTAOs" ThisKey="MANV" OtherKey="MANV" Type="CHUONGTRINHDAOTAO" />
      <Association Name="NHANVIEN_HINHANH" Member="HINHANHs" ThisKey="MANV" OtherKey="MANV" Type="HINHANH" />
      <Association Name="NHANVIEN_PHONGBAN" Member="PHONGBANs" ThisKey="MANV" OtherKey="MATRUONGPHONG" Type="PHONGBAN" />
      <Association Name="NHANVIEN_QUANLYKYLUAT" Member="QUANLYKYLUATs" ThisKey="MANV" OtherKey="MANV" Type="QUANLYKYLUAT" />
      <Association Name="NHANVIEN_QUANLYNGHIVIEC" Member="QUANLYNGHIVIECs" ThisKey="MANV" OtherKey="MANV" Type="QUANLYNGHIVIEC" />
      <Association Name="NHANVIEN_QUANLYTHAISAN" Member="QUANLYTHAISANs" ThisKey="MANV" OtherKey="MANV" Type="QUANLYTHAISAN" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="TAIKHOAN" ThisKey="MANV" OtherKey="MANV" Type="TAIKHOAN" Cardinality="One" />
      <Association Name="NHANVIEN_TONGLUONG" Member="TONGLUONGs" ThisKey="MANV" OtherKey="MANV" Type="TONGLUONG" />
      <Association Name="CHUCVU_NHANVIEN" Member="CHUCVU" ThisKey="MACHUCVU" OtherKey="MACHUCVU" Type="CHUCVU" IsForeignKey="true" />
      <Association Name="HOSOTUYENDUNG_NHANVIEN" Member="HOSOTUYENDUNG" ThisKey="MAHOSO" OtherKey="MAUNGVIEN" Type="HOSOTUYENDUNG" IsForeignKey="true" />
      <Association Name="PHONGBAN_NHANVIEN" Member="PHONGBAN" ThisKey="MAPHONGBAN" OtherKey="MAPHONGBAN" Type="PHONGBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHOMNGUOIDUNG" Member="NHOMNGUOIDUNGs">
    <Type Name="NHOMNGUOIDUNG">
      <Column Name="MANHOM" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NHOMNGUOIDUNG_NGUOIDUNGNHOMNGUOIDUNG" Member="NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="MANHOM" OtherKey="MANHOM" Type="NGUOIDUNGNHOMNGUOIDUNG" />
      <Association Name="NHOMNGUOIDUNG_PHANQUYEN" Member="PHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOM" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MAMANHINH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOM" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MANHINH_PHANQUYEN" Member="MANHINH" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="MANHINH" IsForeignKey="true" />
      <Association Name="NHOMNGUOIDUNG_PHANQUYEN" Member="NHOMNGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGBAN" Member="PHONGBANs">
    <Type Name="PHONGBAN">
      <Column Name="MAPHONGBAN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPHONGBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MATRUONGPHONG" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="PHONGBAN_NHANVIEN" Member="NHANVIENs" ThisKey="MAPHONGBAN" OtherKey="MAPHONGBAN" Type="NHANVIEN" />
      <Association Name="NHANVIEN_PHONGBAN" Member="NHANVIEN" ThisKey="MATRUONGPHONG" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUANLYKYLUAT" Member="QUANLYKYLUATs">
    <Type Name="QUANLYKYLUAT">
      <Column Name="MAQUANLYKYLUAT" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MAKYLUAT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYKYLUAT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="COQUANKYLUAT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DS_KYLUAT_QUANLYKYLUAT" Member="DS_KYLUAT" ThisKey="MAKYLUAT" OtherKey="MAKYLUAT" Type="DS_KYLUAT" IsForeignKey="true" />
      <Association Name="NHANVIEN_QUANLYKYLUAT" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUANLYNGHIVIEC" Member="QUANLYNGHIVIECs">
    <Type Name="QUANLYNGHIVIEC">
      <Column Name="MAQUANLYNGHIVIEC" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SOQUYETDINH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYQUYETDINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGUOIKY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYNGHIVIEC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHANVIEN_QUANLYNGHIVIEC" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUANLYTHAISAN" Member="QUANLYTHAISANs">
    <Type Name="QUANLYTHAISAN">
      <Column Name="MAQUANLYTHAISAN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SOQUYETDINH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SINHCONTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYQUYETDINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="COQUANQUYETDINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYBATDAU" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYKETTHUC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NHANVIEN_QUANLYTHAISAN" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUOCTICH" Member="QUOCTICHes">
    <Type Name="QUOCTICH">
      <Column Name="MAQUOCTICH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENQUOCTICH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QUOCTICH_HOSOTUYENDUNG" Member="HOSOTUYENDUNGs" ThisKey="MAQUOCTICH" OtherKey="MAQUOCTICH" Type="HOSOTUYENDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TAIKHOAN_NGUOIDUNGNHOMNGUOIDUNG" Member="NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="MANV" OtherKey="MANV" Type="NGUOIDUNGNHOMNGUOIDUNG" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TONGIAO" Member="TONGIAOs">
    <Type Name="TONGIAO">
      <Column Name="MATONGIAO" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTONGIAO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TONGIAO_HOSOTUYENDUNG" Member="HOSOTUYENDUNGs" ThisKey="MATONGIAO" OtherKey="MATONGIAO" Type="HOSOTUYENDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.TONGLUONG" Member="TONGLUONGs">
    <Type Name="TONGLUONG">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LUONGTHANG" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TONGTIENLUONG" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="NHANVIEN_TONGLUONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRINHDOHOCVAN" Member="TRINHDOHOCVANs">
    <Type Name="TRINHDOHOCVAN">
      <Column Name="MATRINHDOHOCVAN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTRINHDOHOCVAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TRINHDOHOCVAN_HOSOTUYENDUNG" Member="HOSOTUYENDUNGs" ThisKey="MATRINHDOHOCVAN" OtherKey="MATRINHDOHOCVAN" Type="HOSOTUYENDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.TRINHDOTINHOC" Member="TRINHDOTINHOCs">
    <Type Name="TRINHDOTINHOC">
      <Column Name="MATRINHDOTINHOC" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTRINHDOTINHOC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TRINHDOTINHOC_HOSOTUYENDUNG" Member="HOSOTUYENDUNGs" ThisKey="MATRINHDOTINHOC" OtherKey="MATRINHDOTINHOC" Type="HOSOTUYENDUNG" />
    </Type>
  </Table>
</Database>